components:
  parameters:
    collection:
      name: collection
      in: path
      required: true
      schema:
        type: string
    id:
      name: id
      in: path
      required: true
      description: ID of the item
      schema:
        type : string
    startDate:
      name: start_date
      in: query
      required: true
      description: Date and time of the start of the time-frame
      schema:
        type: string
        format: date-time
    endDate:
      name: end_date
      in: query
      required: true
      description: Date and time of the end of the time-frame
      schema:
        type: string
        format: date-time
    location:
      name: location_id
      in: query
      required: true
      description: ID of the location. Specify -1 to return all items without a location.
      schema:
        type: integer
        format: int32
        minimum: -1
